export enum BiomeTypes {
  DEEP_WATER = 'OCEAN',
  SHOAL = 'RIVER',
  COAST = 'COAST',
  SAVANNA = 'SAVANNA',
  DESERT = 'DESERT',
  FIELD = 'FIELD',
  JUNGLE = 'JUNGLE',
  SWAMP = 'SWAMP',
  FOOTHILLS = 'FOOTHILLS',
  HILLS = 'HILLS',
  PERMAFROST = 'PERMAFROST',
  EMPTY = 'EMPTY'
}
