export enum ClimateTypes {
  POLAR = 'POLAR',
  SUBPOLAR = 'SUBPOLAR',
  TEMPERATE = 'TEMPERATE',
  SUBTEMPERATE = 'SUBTEMPERATE',
  DRY = 'DRY',
  SUBTROPICAL = 'SUBTROPICAL',
  TROPICAL = 'TROPICAL',
}
